import type { BeforeAfterPage } from "../types";

export const beforeAfterPages: BeforeAfterPage[] = [
  {
    slug: "concrete-slab-to-stamped-grey-patio",
    title: "Plain Slab to Stamped Grey Patio - Before & After | PourCanvas",
    headline: "Plain Slab to Stamped Grey Patio",
    metaDescription: "See how a plain concrete slab transforms into a stamped grey patio with an ashlar pattern and antiquing wash. Real before and after results.",
    ogImage: "https://images.pourcanvas.com/before-after-slab-to-stamped-grey.jpg",
    heroAlt: "Before and after: plain concrete slab transformed into a stamped grey ashlar patio",
    contentBlock: "A plain concrete slab becomes a designer outdoor surface with stamped concrete overlay - no demolition required. The ashlar pattern with a grey antiquing wash reads as natural stone from any angle, adding depth and visual weight to a space that previously had none. Stamped overlays typically run $8–14 per sq ft installed on an existing slab in good condition, making this one of the highest-value patio transformations available. The grey tone suits craftsman, contemporary, and colonial exteriors equally well - it's the most versatile colour in the concrete palette. Upload a photo of your patio to see how this transformation could look in your space.",
    pillar: "patio",
    ctaHeadline: "See This on Your Patio",
    ctaBody: "Upload a photo of your patio and see what a stamped grey pattern could look like in your space.",
  },
  {
    slug: "plain-driveway-to-exposed-aggregate",
    title: "Plain Driveway to Exposed Aggregate - Before & After | PourCanvas",
    headline: "Plain Driveway to Exposed Aggregate",
    metaDescription: "See a plain grey driveway transformed into a charcoal exposed aggregate surface. Real before and after with cost context.",
    ogImage: "https://images.pourcanvas.com/before-after-plain-to-exposed-aggregate.jpg",
    heroAlt: "Before and after: plain concrete driveway transformed into an exposed aggregate finish",
    contentBlock: "Exposed aggregate transforms a flat grey driveway into a surface with genuine visual depth - the pebbles catch light differently across the day, and the texture reads as premium from the street. This transformation is achieved by removing the surface paste during cure to reveal the aggregate beneath, or by applying an aggregate seeding overlay to an existing slab. Typical cost runs $6–12 per sq ft, depending on aggregate type and driveway size. Charcoal aggregate is the top-performing finish for contemporary and transitional homes - it holds colour well and the dark tone masks tyre marks and dirt between cleans. See how it could look on your driveway.",
    pillar: "driveway",
    ctaHeadline: "See This on Your Driveway",
    ctaBody: "Upload a photo of your driveway and see what an exposed aggregate finish could look like in your space.",
  },
  {
    slug: "cracked-walkway-to-flagstone",
    title: "Cracked Walkway to Flagstone Look - Before & After | PourCanvas",
    headline: "Cracked Walkway to Flagstone Look",
    metaDescription: "A cracked concrete walkway replaced with a stamped flagstone finish. See the transformation and what it costs.",
    ogImage: "https://images.pourcanvas.com/before-after-cracked-to-flagstone.jpg",
    heroAlt: "Before and after: cracked concrete walkway replaced with a stamped flagstone look",
    contentBlock: "A cracked or settled walkway doesn't have to mean a full excavation and pour. Stamped concrete overlays in a flagstone pattern can resurface a structurally sound path for a fraction of full replacement cost - typically $10–16 per sq ft versus $18–30 for new pour plus disposal. The flagstone pattern works particularly well for craftsman, ranch, and cottage-style homes where the organic irregular slab shape fits the architecture naturally. The surface is sealed against water infiltration which extends the life of the path and prevents future cracking from freeze-thaw cycles. Upload a photo of your front path to see how the flagstone look could work.",
    pillar: "walkway",
    ctaHeadline: "See This on Your Walkway",
    ctaBody: "Upload a photo of your walkway and see what a flagstone stamped finish could look like in your space.",
  },
  {
    slug: "plain-patio-to-herringbone-brick",
    title: "Plain Patio to Herringbone Brick Look - Before & After | PourCanvas",
    headline: "Plain Patio to Herringbone Brick",
    metaDescription: "A plain concrete patio transformed into a herringbone brick stamped pattern. See the before and after and typical project cost.",
    ogImage: "https://images.pourcanvas.com/before-after-plain-to-herringbone-brick.jpg",
    heroAlt: "Before and after: plain concrete patio transformed into a herringbone brick stamped pattern",
    contentBlock: "The herringbone brick pattern is one of the most recognisable patio transformations - a plain grey slab gains a classic interlocking geometry that reads as real brick from any distance. Stamped concrete achieves this at roughly half the material cost of actual clay brick pavers, with no joint maintenance or weed growth between units. The pattern works at any scale but looks especially strong on larger patios where the diagonal geometry creates natural sight lines. Red-brown and buff antiquing washes suit traditional and colonial homes; grey washes are the right call for craftsman and transitional styles. See how the herringbone pattern could transform your patio.",
    pillar: "patio",
    ctaHeadline: "See This on Your Patio",
    ctaBody: "Upload a photo of your patio and see what a herringbone brick stamped pattern could look like in your space.",
  },
  {
    slug: "broom-finish-to-stamped-cobblestone-driveway",
    title: "Broom Finish to Stamped Cobblestone Driveway - Before & After | PourCanvas",
    headline: "Broom Finish to Stamped Cobblestone",
    metaDescription: "A standard broom-finish driveway transformed into a stamped cobblestone surface. See the visual impact and what the upgrade costs.",
    ogImage: "https://images.pourcanvas.com/before-after-broom-to-stamped-cobblestone.jpg",
    heroAlt: "Before and after: broom finish driveway transformed into a stamped cobblestone surface",
    contentBlock: "A standard broom-finish driveway is functional but forgettable. The cobblestone stamp pattern transforms the same surface into one that looks custom-built - the rounded irregular units with a grey and buff antiquing wash read as genuine European cobblestone from the street. This upgrade is most impactful on longer driveways where the pattern can repeat and develop visual rhythm. Cobblestone suits colonial, Tudor, and traditional home styles naturally; it also works for craftsman exteriors when paired with a neutral buff wash rather than dark antiquing. The sealed surface resists oil stains and tyre marks better than unsealed broom finish. See the cobblestone look on your driveway.",
    pillar: "driveway",
    ctaHeadline: "See This on Your Driveway",
    ctaBody: "Upload a photo of your driveway and see what a stamped cobblestone finish could look like in your space.",
  },
];
