import type { BeforeAfterPage } from "../types";

export const beforeAfterPages: BeforeAfterPage[] = [
  {
    slug: "concrete-slab-to-stamped-grey-patio",
    title: "Plain Slab to Stamped Grey Patio - Before & After | PourCanvas",
    headline: "Plain Slab to Stamped Grey Patio",
    metaDescription: "Plain concrete slab to stamped grey ashlar patio — stamped overlay at $8–14/sq ft, no demolition. See the before and after transformation.",
    ogImage: "https://images.pourcanvas.com/before-after-slab-to-stamped-grey.jpg",
    heroAlt: "Before and after: plain concrete slab transformed into a stamped grey ashlar patio",
    contentBlock: "A plain concrete slab becomes a designer outdoor surface with a stamped concrete overlay — no demolition required. The ashlar pattern with a grey antiquing wash reads as natural stone from any angle, adding depth and visual weight to a space that previously had none.\n\nStamped overlays on an existing slab in sound condition typically run $8–14 per sq ft installed, making this one of the highest-value patio transformations available. Compare that to full demolition and repour, which adds $4–7 per sq ft in removal and disposal costs alone — on a 300 sq ft patio, the overlay approach saves $1,200–$2,100 before the stamping cost is even factored in.\n\nThe grey ashlar finish suits this use case because the large irregular slab shapes give a mid-sized patio genuine architectural scale. It doesn't read as a pattern the way herringbone or cobblestone does — it reads as material. The cooler grey tone works equally well on craftsman, contemporary, and colonial exteriors, which makes it the most versatile choice in the concrete palette when you're not certain of your exterior colour direction.\n\nThe sealed surface resists UV fade, moisture infiltration, and surface staining from outdoor furniture. Upload a photo of your patio to see how this transformation could look in your specific space.",
    pillar: "patio",
    ctaHeadline: "See This on Your Patio",
    ctaBody: "Upload a photo of your patio and see what a stamped grey ashlar pattern could look like on your concrete slab.",
  },
  {
    slug: "plain-driveway-to-exposed-aggregate",
    title: "Plain Driveway to Exposed Aggregate - Before & After | PourCanvas",
    headline: "Plain Driveway to Exposed Aggregate",
    metaDescription: "Plain grey driveway to charcoal exposed aggregate — $6–12/sq ft installed, genuine texture and depth. Real before and after with cost context.",
    ogImage: "https://images.pourcanvas.com/before-after-plain-to-exposed-aggregate.jpg",
    heroAlt: "Before and after: plain concrete driveway transformed into an exposed aggregate finish",
    contentBlock: "Exposed aggregate transforms a flat grey driveway into a surface with genuine visual depth — the pebbles catch light differently across the day, and the texture reads as premium from the street in a way no stamped pattern quite achieves.\n\nThis transformation is achieved by removing the surface paste during cure to reveal the decorative aggregate beneath, or by applying an aggregate seeding overlay to an existing slab. Typical installed cost runs $6–12 per sq ft depending on aggregate type and driveway size. On a standard two-car driveway (400–500 sq ft), the total project cost falls between $2,400 and $6,000 — roughly half what full demolition, repour, and decorative overlay would cost.\n\nCharcoal aggregate suits this use case because driveways collect tyre marks, oil residue, and leaf staining between cleans. The dark irregular surface tone visually absorbs minor marks rather than highlighting them the way a plain grey or buff slab does. The exposed stone texture also provides natural slip resistance without an additive — an important practical advantage over sealed stamped concrete on a sloped driveway approach.\n\nThe finish holds its colour well under UV exposure and heavy vehicle traffic. Charcoal pairs cleanly with contemporary, transitional, and craftsman exteriors. Upload a photo of your driveway to see how the exposed aggregate finish could look on your specific surface.",
    pillar: "driveway",
    ctaHeadline: "See This on Your Driveway",
    ctaBody: "Upload a photo of your driveway and see what a charcoal exposed aggregate finish could look like on your concrete surface.",
  },
  {
    slug: "cracked-walkway-to-flagstone",
    title: "Cracked Walkway to Flagstone Look - Before & After | PourCanvas",
    headline: "Cracked Walkway to Flagstone Look",
    metaDescription: "Cracked concrete walkway to stamped flagstone look — overlay at $10–16/sq ft, no excavation needed. See the before and after transformation.",
    ogImage: "https://images.pourcanvas.com/before-after-cracked-to-flagstone.jpg",
    heroAlt: "Before and after: cracked concrete walkway replaced with a stamped flagstone look",
    contentBlock: "A cracked or settled walkway doesn't have to mean a full excavation and pour. A stamped concrete overlay in a flagstone pattern can resurface a structurally sound path at a fraction of full replacement cost — typically $10–16 per sq ft installed, versus $18–30 per sq ft for complete demolition, subbase work, and repour with disposal fees. On a 60 sq ft front walkway, that difference can be $480–$840 in direct savings, with no weeks of torn-up yard access.\n\nThe flagstone pattern suits walkways particularly well because the organic, irregular stone shape reads as naturally laid rather than poured — a quality that matters more on an entry path, where visitors are walking slowly at eye level, than it does on a large patio viewed from a distance. The visual weight of the individual slab shapes gives a narrow path genuine character without needing width or complexity.\n\nFor craftsman, ranch, cottage, and traditional home styles, the flagstone pattern is the most architecturally coherent concrete finish available. It fits without competing with brick, timber, or natural-stone accent elements that appear on those home styles. Warm buff and sandstone washes suit traditional exteriors; charcoal and slate washes work for contemporary and transitional homes.\n\nThe sealed overlay surface prevents water infiltration at the existing crack lines, which stops future freeze-thaw expansion from widening surface damage. Upload a photo of your front path to see how the flagstone finish could look in your specific space.",
    pillar: "walkway",
    ctaHeadline: "See This on Your Walkway",
    ctaBody: "Upload a photo of your walkway and see what a stamped flagstone overlay could look like on your concrete path.",
  },
  {
    slug: "plain-patio-to-herringbone-brick",
    title: "Plain Patio to Herringbone Brick Look - Before & After | PourCanvas",
    headline: "Plain Patio to Herringbone Brick",
    metaDescription: "A plain concrete patio transformed into a herringbone brick stamped pattern. See the before and after and typical project cost.",
    ogImage: "https://images.pourcanvas.com/before-after-plain-to-herringbone-brick.jpg",
    heroAlt: "Before and after: plain concrete patio transformed into a herringbone brick stamped pattern",
    contentBlock: "The herringbone brick pattern transforms a plain concrete slab into a surface with classic interlocking geometry — the diagonal layout draws the eye across the space and makes a mid-sized patio feel deliberately designed rather than incidental. Unlike real clay brick pavers, stamped concrete achieves the same look as a continuous sealed slab: no mortar joints to weed, no individual units to shift or settle, and no risk of frost heave disrupting the pattern over time.\n\nCost for a stamped herringbone overlay on an existing slab in sound condition typically runs $10–16 per sq ft, compared to $20–30 per sq ft for full demolition, new pour, and real brick paver installation. On a 300 sq ft patio, that's a difference of $3,000–$4,200 for a result most guests won't distinguish from real brick at normal viewing distance.\n\nThe pattern suits this use case because herringbone's tight geometry reads at its best underfoot on a flat patio surface — the interlocking angles create visual structure that a larger, more open finish like ashlar slate can't provide in a compact space. Red-brown and buff antiquing washes suit traditional and colonial homes; grey washes are the right choice for craftsman and transitional exteriors.\n\nIf you're weighing finishes for your patio, upload a photo to see how the herringbone brick pattern could look in your specific space.",
    pillar: "patio",
    ctaHeadline: "See This on Your Patio",
    ctaBody: "Upload a photo of your patio and see what a herringbone brick stamped pattern could look like in your space.",
  },
  {
    slug: "broom-finish-to-stamped-cobblestone-driveway",
    title: "Broom Finish to Stamped Cobblestone Driveway - Before & After | PourCanvas",
    headline: "Broom Finish to Stamped Cobblestone",
    metaDescription: "A standard broom-finish driveway transformed into a stamped cobblestone surface. See the visual impact and what the upgrade costs.",
    ogImage: "https://images.pourcanvas.com/before-after-broom-to-stamped-cobblestone.jpg",
    heroAlt: "Before and after: broom finish driveway transformed into a stamped cobblestone surface",
    contentBlock: "A standard broom-finish driveway is functional but forgettable — it reads as infrastructure, not design. Upgrading to a stamped cobblestone finish transforms the same slab into a surface that reads as custom-built from the street: rounded irregular units with a grey and buff antiquing wash that closely mimics genuine European cobblestone, without the maintenance demands of real stone or the settlement risk of individual pavers.\n\nThis transformation is achieved by applying a stamped overlay to the existing concrete — typically $10–16 per sq ft installed on a slab in sound condition — compared to $25–40 per sq ft for full demolition, repour, and real cobblestone installation. On a 600 sq ft two-car driveway, that difference can be $9,000–$14,000. The overlay bonds directly to the existing slab, meaning no disposal costs and no weeks-long installation disruption.\n\nThe cobblestone pattern suits this use case because driveways benefit from a surface that signals quality from a distance. The tight, repeating geometry of cobblestone develops visual rhythm as the pattern extends down a longer drive — the longer the driveway, the more impactful the finish. Colonial, Tudor, and traditional home styles are the natural fit; craftsman and transitional exteriors also work well when paired with a neutral buff wash rather than dark antiquing.\n\nThe sealed surface resists oil stains and tyre marks better than unsealed broom finish, and the colour is UV-stabilised to hold its depth over time. If you're weighing this upgrade, upload a photo of your driveway to see how the cobblestone stamp could look on your specific surface.",
    pillar: "driveway",
    ctaHeadline: "See This on Your Driveway",
    ctaBody: "Upload a photo of your driveway and see what a stamped cobblestone finish could look like in your space.",
  },
];
