import type { PalettePage } from "../types";

export const palettePages: PalettePage[] = [
  {
    slug: "warm-grey-patio",
    title: "Warm Grey Patio Color Palette | PourCanvas",
    headline: "Warm Grey Patio Palette",
    metaDescription: "Warm grey concrete patio tones - from soft dove to deep charcoal with warm undertones. See how this palette looks across different home styles.",
    ogImage: "https://images.pourcanvas.com/palette-warm-grey-patio.jpg",
    heroAlt: "Warm grey concrete patio color palette showing tonal range from light dove to deep charcoal",
    contentBlock: "Warm grey is the most versatile patio colour available - it reads as neutral without the coolness of blue-grey or the flatness of true concrete. The warm undertone (pulling slightly toward buff or beige) means it pairs naturally with timber decking, brick surrounds, and sandstone garden walls without clashing. On stained concrete, warm grey develops through an integral pigment mix or acid stain process. On stamped surfaces, the same tone is achieved with a combination of base colour and antiquing wash. The palette shown moves from a light dove suitable for small patios that benefit from visual expansion, through a mid warm grey that suits most suburban settings, to a deep charcoal-warm for contemporary homes where the patio is a design statement. Upload a photo of your patio to preview any of these tones in your space.",
    pillar: "patio",
    ctaHeadline: "Preview This Palette on Your Patio",
    ctaBody: "Upload a photo of your patio and see how the warm grey palette could look in your space.",
  },
  {
    slug: "charcoal-driveway",
    title: "Charcoal Driveway Color Palette | PourCanvas",
    headline: "Charcoal Driveway Palette",
    metaDescription: "Charcoal concrete driveway tones - from dark mid-grey to near-black. See how this high-contrast palette pairs with different home exteriors.",
    ogImage: "https://images.pourcanvas.com/palette-charcoal-driveway.jpg",
    heroAlt: "Charcoal driveway color palette showing tonal range from mid dark grey to near-black",
    contentBlock: "Charcoal driveways create the sharpest street-side contrast available in concrete - the dark tone makes white, cream, and light grey home exteriors pop and gives contemporary homes a deliberate, architectural quality. The palette range shown moves from a deep mid-grey (the safest charcoal for traditional and colonial homes) through to a near-black (reserved for modern flat-roof and contemporary homes where the driveway is part of the architectural statement). Charcoal is typically achieved through integral dark pigment in the concrete mix or dark acid stain on an existing slab. On exposed aggregate driveways, charcoal aggregate is mixed at the surface layer for a consistent dark tone that doesn't fade with UV over time. See how charcoal would look on your driveway.",
    pillar: "driveway",
    ctaHeadline: "Preview This Palette on Your Driveway",
    ctaBody: "Upload a photo of your driveway and see how the charcoal palette could look in your space.",
  },
  {
    slug: "buff-cream-walkway",
    title: "Buff and Cream Walkway Color Palette | PourCanvas",
    headline: "Buff and Cream Walkway Palette",
    metaDescription: "Buff and cream concrete walkway tones - warm, natural, and welcoming. See how this palette pairs with brick, timber, and stone home fronts.",
    ogImage: "https://images.pourcanvas.com/palette-buff-cream-walkway.jpg",
    heroAlt: "Buff and cream walkway color palette showing warm natural tones from light cream to golden buff",
    contentBlock: "Buff and cream are the warmest tones in the concrete palette - they evoke natural limestone and sandstone without the maintenance of real stone. This palette works particularly well on front entry walkways where the goal is an inviting, soft approach to the door rather than a bold design statement. Cream sits at the lighter end (almost white in full sun) and suits white-painted and light-rendered homes. Buff moves into golden territory and pairs naturally with red brick, sandstone cladding, and timber accents. Both tones are achieved through integral pigment in new pours or warm-toned acid stain on existing slabs. On stamped walkways, a buff base with cream antiquing wash creates a mottled natural stone effect. Preview the buff-cream palette on your front path.",
    pillar: "walkway",
    ctaHeadline: "Preview This Palette on Your Walkway",
    ctaBody: "Upload a photo of your walkway and see how the buff and cream palette could look in your space.",
  },
  {
    slug: "terracotta-outdoor-palette",
    title: "Terracotta Outdoor Concrete Palette | PourCanvas",
    headline: "Terracotta Outdoor Palette",
    metaDescription: "Terracotta and warm red-orange concrete tones for patios and outdoor surfaces. See how this Mediterranean palette suits different home styles.",
    ogImage: "https://images.pourcanvas.com/palette-terracotta-outdoor.jpg",
    heroAlt: "Terracotta outdoor concrete color palette showing warm red-orange tones from light clay to deep burnt sienna",
    contentBlock: "Terracotta is the strongest visual statement in the concrete colour palette - warm, earthy, and unmistakably Mediterranean. The range moves from a light clay-orange (close to natural unglazed terracotta tile) through to a deep burnt sienna that reads almost red in direct sun. Lighter terracotta suits Spanish colonial, hacienda, and stucco homes where the warm colour fits the architectural language. Deeper tones work for contemporary homes where the patio is intended as a colour-forward design element. Terracotta concrete is achieved through iron oxide pigments - the colour is UV-stable and does not fade significantly over time, unlike painted surfaces. On stamped patios, terracotta is often combined with a dark brown antiquing wash to deepen the joints and add tonal complexity. See the terracotta palette on your outdoor surface.",
    pillar: "patio",
    ctaHeadline: "Preview This Palette on Your Patio",
    ctaBody: "Upload a photo of your outdoor space and see how the terracotta palette could look in your space.",
  },
  {
    slug: "slate-blue-walkway-palette",
    title: "Slate Blue Walkway Color Palette | PourCanvas",
    headline: "Slate Blue Walkway Palette",
    metaDescription: "Slate blue and blue-grey concrete walkway tones. See how this cool, architectural palette pairs with modern and coastal home styles.",
    ogImage: "https://images.pourcanvas.com/palette-slate-blue-walkway.jpg",
    heroAlt: "Slate blue walkway color palette showing cool blue-grey tones from pale slate to deep blue-charcoal",
    contentBlock: "Slate blue is the most architectural concrete tone available - a cool blue-grey that reads as deliberately chosen rather than default. The palette moves from a pale slate (close to the natural colour of real slate tile) through to a deep blue-charcoal that suits coastal and contemporary homes strongly. Pale slate works for any modern or transitional home exterior where the goal is a clean, sophisticated front path. Mid slate blue pairs naturally with white render, dark timber, and raw steel architectural details. Deep blue-charcoal is for homes where the walkway is a design feature - it's a bold choice that photographs exceptionally well. Slate blue tones are achieved through blue-tinted integral pigment or blue-grey acid stain. On exposed aggregate paths, blue-grey stone aggregate creates a similar effect. Preview the slate blue palette on your walkway.",
    pillar: "walkway",
    ctaHeadline: "Preview This Palette on Your Walkway",
    ctaBody: "Upload a photo of your walkway and see how the slate blue palette could look in your space.",
  },
];
